services:
  app:
    image: api:v1
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=8000
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: sh -c "cd /app/src && uvicorn main:app --host=0.0.0.0 --port=8000 --reload"
    volumes:
      - ./src/:/app/src:rw
    develop:
      watch:
        - path: Dockerfile
          action: rebuild
        - path: pyproject.toml
          action: rebuild
        - path: docker-compose.yaml
          action: rebuild
